_name_or_path:
    value: /root/autodl-tmp/musicgen-large
_wandb:
    value:
        cli_version: 0.19.11
        m:
            - "1": train/global_step
              "6":
                - 3
              "7": []
            - "1": train/loss
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": train/grad_norm
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": train/learning_rate
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": train/epoch
              "5": 1
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.10.8
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 98
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
                - 98
            "3":
                - 2
                - 7
                - 13
                - 15
                - 16
                - 19
                - 23
                - 55
                - 62
                - 66
            "4": 3.10.8
            "5": 0.19.11
            "6": 4.52.3
            "8":
                - 1
                - 5
            "9":
                "1": transformers_trainer
            "12": 0.19.11
            "13": linux-x86_64
accelerator_config:
    value:
        dispatch_batches: null
        even_batches: true
        gradient_accumulation_kwargs: null
        non_blocking: false
        split_batches: false
        use_seedable_sampler: true
adafactor:
    value: false
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_epsilon:
    value: 1e-08
add_cross_attention:
    value: false
architectures:
    value:
        - MusicgenForConditionalGeneration
audio_encoder:
    value:
        _name_or_path: facebook/encodec_32khz
        add_cross_attention: false
        architectures:
            - EncodecModel
        audio_channels: 1
        bad_words_ids: null
        begin_suppress_tokens: null
        bos_token_id: null
        chunk_length_s: null
        chunk_size_feed_forward: 0
        codebook_dim: 128
        codebook_size: 2048
        compress: 2
        cross_attention_hidden_size: null
        decoder_start_token_id: null
        dilation_growth_rate: 2
        diversity_penalty: 0
        do_sample: false
        early_stopping: false
        encoder_no_repeat_ngram_size: 0
        eos_token_id: null
        exponential_decay_length_penalty: null
        finetuning_task: null
        forced_bos_token_id: null
        forced_eos_token_id: null
        hidden_size: 128
        id2label:
            "0": LABEL_0
            "1": LABEL_1
        is_decoder: false
        is_encoder_decoder: false
        kernel_size: 7
        label2id:
            LABEL_0: 0
            LABEL_1: 1
        last_kernel_size: 7
        length_penalty: 1
        max_length: 20
        min_length: 0
        model_type: encodec
        no_repeat_ngram_size: 0
        norm_type: weight_norm
        normalize: false
        num_beam_groups: 1
        num_beams: 1
        num_filters: 64
        num_lstm_layers: 2
        num_residual_layers: 1
        num_return_sequences: 1
        output_attentions: false
        output_hidden_states: false
        output_scores: false
        overlap: null
        pad_mode: reflect
        pad_token_id: null
        prefix: null
        problem_type: null
        remove_invalid_values: false
        repetition_penalty: 1
        residual_kernel_size: 3
        return_dict: true
        return_dict_in_generate: false
        sampling_rate: 32000
        sep_token_id: null
        suppress_tokens: null
        target_bandwidths:
            - 2.2
        task_specific_params: null
        temperature: 1
        tf_legacy_loss: false
        tie_encoder_decoder: false
        tie_word_embeddings: true
        tokenizer_class: null
        top_k: 50
        top_p: 1
        torch_dtype: float32
        torchscript: false
        trim_right_ratio: 1
        typical_p: 1
        upsampling_ratios:
            - 8
            - 5
            - 4
            - 4
        use_bfloat16: false
        use_causal_conv: false
        use_conv_shortcut: false
auto_find_batch_size:
    value: false
average_tokens_across_devices:
    value: false
bad_words_ids:
    value: null
batch_eval_metrics:
    value: false
batch_size:
    value: 16
begin_suppress_tokens:
    value: null
bf16:
    value: false
bf16_full_eval:
    value: false
bos_token_id:
    value: null
chunk_size_feed_forward:
    value: 0
cross_attention_hidden_size:
    value: null
data_seed:
    value: null
dataloader_drop_last:
    value: false
dataloader_num_workers:
    value: 2
dataloader_persistent_workers:
    value: false
dataloader_pin_memory:
    value: true
dataloader_prefetch_factor:
    value: 2
dataset:
    value: Chinese National Pentatonic Mode
ddp_backend:
    value: null
ddp_broadcast_buffers:
    value: null
ddp_bucket_cap_mb:
    value: null
ddp_find_unused_parameters:
    value: null
ddp_timeout:
    value: 1800
debug:
    value: []
decoder:
    value:
        _name_or_path: ""
        activation_dropout: 0
        activation_function: gelu
        add_cross_attention: false
        architectures: null
        attention_dropout: 0
        audio_channels: 1
        bad_words_ids: null
        begin_suppress_tokens: null
        bos_token_id: 2048
        chunk_size_feed_forward: 0
        classifier_dropout: 0
        cross_attention_hidden_size: null
        decoder_start_token_id: 2048
        diversity_penalty: 0
        do_sample: false
        dropout: 0.1
        early_stopping: false
        encoder_no_repeat_ngram_size: 0
        eos_token_id: null
        exponential_decay_length_penalty: null
        ffn_dim: 8192
        finetuning_task: null
        forced_bos_token_id: null
        forced_eos_token_id: null
        hidden_size: 2048
        id2label:
            "0": LABEL_0
            "1": LABEL_1
        initializer_factor: 0.02
        is_decoder: false
        is_encoder_decoder: false
        label2id:
            LABEL_0: 0
            LABEL_1: 1
        layerdrop: 0
        length_penalty: 1
        max_length: 20
        max_position_embeddings: 2048
        min_length: 0
        model_type: musicgen_decoder
        no_repeat_ngram_size: 0
        num_attention_heads: 32
        num_beam_groups: 1
        num_beams: 1
        num_codebooks: 4
        num_hidden_layers: 48
        num_return_sequences: 1
        output_attentions: false
        output_hidden_states: false
        output_scores: false
        pad_token_id: 2048
        prefix: null
        problem_type: null
        remove_invalid_values: false
        repetition_penalty: 1
        return_dict: true
        return_dict_in_generate: false
        scale_embedding: false
        sep_token_id: null
        suppress_tokens: null
        task_specific_params: null
        temperature: 1
        tf_legacy_loss: false
        tie_encoder_decoder: false
        tie_word_embeddings: false
        tokenizer_class: null
        top_k: 50
        top_p: 1
        torch_dtype: float32
        torchscript: false
        typical_p: 1
        use_bfloat16: false
        use_cache: true
        vocab_size: 2048
decoder_start_token_id:
    value: null
deepspeed:
    value: null
disable_tqdm:
    value: false
diversity_penalty:
    value: 0
do_eval:
    value: true
do_predict:
    value: false
do_sample:
    value: false
do_train:
    value: false
early_stopping:
    value: false
encoder_no_repeat_ngram_size:
    value: 0
eos_token_id:
    value: null
eval_accumulation_steps:
    value: null
eval_delay:
    value: 0
eval_do_concat_batches:
    value: true
eval_on_start:
    value: false
eval_steps:
    value: 250
eval_strategy:
    value: steps
eval_use_gather_object:
    value: false
exponential_decay_length_penalty:
    value: null
finetuning_task:
    value: null
forced_bos_token_id:
    value: null
forced_eos_token_id:
    value: null
fp16:
    value: true
fp16_backend:
    value: auto
fp16_full_eval:
    value: false
fp16_opt_level:
    value: O1
fsdp:
    value: []
fsdp_config:
    value:
        min_num_params: 0
        xla: false
        xla_fsdp_grad_ckpt: false
        xla_fsdp_v2: false
fsdp_min_num_params:
    value: 0
fsdp_transformer_layer_cls_to_wrap:
    value: null
full_determinism:
    value: false
gpu:
    value: A100-80GB
gradient_accumulation_steps:
    value: 4
gradient_checkpointing:
    value: false
gradient_checkpointing_kwargs:
    value: null
greater_is_better:
    value: false
group_by_length:
    value: false
half_precision_backend:
    value: auto
hub_always_push:
    value: false
hub_model_id:
    value: null
hub_private_repo:
    value: null
hub_strategy:
    value: every_save
hub_token:
    value: <HUB_TOKEN>
id2label:
    value:
        "0": LABEL_0
        "1": LABEL_1
ignore_data_skip:
    value: false
include_for_metrics:
    value: []
include_inputs_for_metrics:
    value: false
include_num_input_tokens_seen:
    value: false
include_tokens_per_second:
    value: false
is_decoder:
    value: false
is_encoder_decoder:
    value: true
jit_mode_eval:
    value: false
label_names:
    value:
        - labels
label_smoothing_factor:
    value: 0
label2id:
    value:
        LABEL_0: 0
        LABEL_1: 1
learning_rate:
    value: 0.0002
length_column_name:
    value: length
length_penalty:
    value: 1
load_best_model_at_end:
    value: true
local_rank:
    value: 0
log_level:
    value: passive
log_level_replica:
    value: warning
log_on_each_node:
    value: true
logging_dir:
    value: ./logs
logging_first_step:
    value: false
logging_nan_inf_filter:
    value: true
logging_steps:
    value: 10
logging_strategy:
    value: steps
lora_alpha:
    value: 32
lora_rank:
    value: 16
lr_scheduler_type:
    value: cosine
max_grad_norm:
    value: 1
max_length:
    value: 20
max_steps:
    value: -1
metric_for_best_model:
    value: eval_loss
min_length:
    value: 0
model:
    value: musicgen-large
model/num_parameters:
    value: 3436053058
model_type:
    value: musicgen
mp_parameters:
    value: ""
neftune_noise_alpha:
    value: null
no_cuda:
    value: false
no_repeat_ngram_size:
    value: 0
num_beam_groups:
    value: 1
num_beams:
    value: 1
num_epochs:
    value: 5
num_return_sequences:
    value: 1
num_train_epochs:
    value: 5
optim:
    value: adamw_torch
optim_args:
    value: null
optim_target_modules:
    value: null
output_attentions:
    value: false
output_dir:
    value: ./outputs/musicgen-lora
output_hidden_states:
    value: false
output_scores:
    value: false
overwrite_output_dir:
    value: false
pad_token_id:
    value: null
past_index:
    value: -1
peft_config:
    value:
        default:
            auto_mapping: null
            base_model_name_or_path: /root/autodl-tmp/musicgen-large
            bias: none
            corda_config: null
            eva_config: null
            exclude_modules: null
            fan_in_fan_out: false
            inference_mode: false
            init_lora_weights: true
            layer_replication: null
            layers_pattern: null
            layers_to_transform: null
            lora_alpha: 32
            lora_bias: false
            lora_dropout: 0.05
            megatron_config: null
            megatron_core: megatron.core
            modules_to_save: null
            peft_type: LORA
            r: 8
            revision: null
            runtime_config:
                ephemeral_gpu_offload: false
            target_modules:
                - v_proj
                - q_proj
                - k_proj
                - out_proj
            task_type: CAUSAL_LM
            trainable_token_indices: null
            use_dora: false
            use_rslora: false
per_device_eval_batch_size:
    value: 8
per_device_train_batch_size:
    value: 8
per_gpu_eval_batch_size:
    value: null
per_gpu_train_batch_size:
    value: null
prediction_loss_only:
    value: false
prefix:
    value: null
problem_type:
    value: null
push_to_hub:
    value: false
push_to_hub_model_id:
    value: null
push_to_hub_organization:
    value: null
push_to_hub_token:
    value: <PUSH_TO_HUB_TOKEN>
ray_scope:
    value: last
remove_invalid_values:
    value: false
remove_unused_columns:
    value: false
repetition_penalty:
    value: 1
report_to:
    value:
        - wandb
restore_callback_states_from_checkpoint:
    value: false
resume_from_checkpoint:
    value: null
return_dict:
    value: true
return_dict_in_generate:
    value: false
run_name:
    value: ./outputs/musicgen-lora
save_on_each_node:
    value: false
save_only_model:
    value: false
save_safetensors:
    value: true
save_steps:
    value: 500
save_strategy:
    value: steps
save_total_limit:
    value: 3
seed:
    value: 42
sep_token_id:
    value: null
skip_memory_metrics:
    value: true
suppress_tokens:
    value: null
task_specific_params:
    value: null
temperature:
    value: 1
text_encoder:
    value:
        _name_or_path: t5-base
        add_cross_attention: false
        architectures:
            - T5ForConditionalGeneration
        bad_words_ids: null
        begin_suppress_tokens: null
        bos_token_id: null
        chunk_size_feed_forward: 0
        classifier_dropout: 0
        cross_attention_hidden_size: null
        d_ff: 3072
        d_kv: 64
        d_model: 768
        decoder_start_token_id: 0
        dense_act_fn: relu
        diversity_penalty: 0
        do_sample: false
        dropout_rate: 0.1
        early_stopping: false
        encoder_no_repeat_ngram_size: 0
        eos_token_id: 1
        exponential_decay_length_penalty: null
        feed_forward_proj: relu
        finetuning_task: null
        forced_bos_token_id: null
        forced_eos_token_id: null
        id2label:
            "0": LABEL_0
            "1": LABEL_1
        initializer_factor: 1
        is_decoder: false
        is_encoder_decoder: true
        is_gated_act: false
        label2id:
            LABEL_0: 0
            LABEL_1: 1
        layer_norm_epsilon: 1e-06
        length_penalty: 1
        max_length: 20
        min_length: 0
        model_type: t5
        n_positions: 512
        no_repeat_ngram_size: 0
        num_beam_groups: 1
        num_beams: 1
        num_decoder_layers: 12
        num_heads: 12
        num_layers: 12
        num_return_sequences: 1
        output_attentions: false
        output_hidden_states: false
        output_past: true
        output_scores: false
        pad_token_id: 0
        prefix: null
        problem_type: null
        relative_attention_max_distance: 128
        relative_attention_num_buckets: 32
        remove_invalid_values: false
        repetition_penalty: 1
        return_dict: true
        return_dict_in_generate: false
        sep_token_id: null
        suppress_tokens: null
        task_specific_params:
            summarization:
                early_stopping: true
                length_penalty: 2
                max_length: 200
                min_length: 30
                no_repeat_ngram_size: 3
                num_beams: 4
                prefix: 'summarize: '
            translation_en_to_de:
                early_stopping: true
                max_length: 300
                num_beams: 4
                prefix: 'translate English to German: '
            translation_en_to_fr:
                early_stopping: true
                max_length: 300
                num_beams: 4
                prefix: 'translate English to French: '
            translation_en_to_ro:
                early_stopping: true
                max_length: 300
                num_beams: 4
                prefix: 'translate English to Romanian: '
        temperature: 1
        tf_legacy_loss: false
        tie_encoder_decoder: false
        tie_word_embeddings: true
        tokenizer_class: null
        top_k: 50
        top_p: 1
        torch_dtype: float32
        torchscript: false
        typical_p: 1
        use_bfloat16: false
        use_cache: true
        vocab_size: 32128
tf_legacy_loss:
    value: false
tf32:
    value: null
tie_encoder_decoder:
    value: false
tie_word_embeddings:
    value: true
tokenizer_class:
    value: null
top_k:
    value: 50
top_p:
    value: 1
torch_compile:
    value: false
torch_compile_backend:
    value: null
torch_compile_mode:
    value: null
torch_dtype:
    value: float32
torch_empty_cache_steps:
    value: null
torchdynamo:
    value: null
torchscript:
    value: false
tpu_metrics_debug:
    value: false
tpu_num_cores:
    value: null
transformers_version:
    value: 4.52.3
typical_p:
    value: 1
use_bfloat16:
    value: false
use_cpu:
    value: false
use_ipex:
    value: false
use_legacy_prediction_loop:
    value: false
use_liger_kernel:
    value: false
use_mps_device:
    value: false
warmup_ratio:
    value: 0
warmup_steps:
    value: 200
weight_decay:
    value: 0.01
